version: '3.8'

services:
  identity-service:
    build: .
    ports:
      - "8080:8080"
    environment:
      - HTTP_ADDR=:8080
      - JWT_SECRET=your-super-secret-jwt-key-change-this-in-production
      - TOKEN_TTL_SECONDS=900
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  # Future: Add PostgreSQL database
  # db:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: identity
  #     POSTGRES_USER: identity
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data: 